id: AD49C0999
title: Toh_11-The_Transcendent_Perfection_of_Wisdom_in_Ten_Thousand_Lines-v1
type: translation
pechas:
- IDD210D89
- I010CD9DB
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-03-23T18:02:40.517Z'
  creationid: CW
  eft-text-id: UT22084-031-002
  xmlns-eft: http://read.84000.co/ns/1.0
  title: Toh_11-The_Transcendent_Perfection_of_Wisdom_in_Ten_Thousand_Lines-v1
alignment_to_base:
  IDD210D89/2E8C: 5E2A
  I010CD9DB/030A: 5E2A
